<html>
<title>C.A.N.O.B</title>
<head>Club Atletico Newell's Old Boys</head>
<header>Esta Es Una Web Leprosa</header>
<body>
<div>
<form>
    <h1>Formulario de registro leproso</h1>
<div>
<label for="Nombre">¿Cual es tu nombre lepra?</label>
<input id="Nombre" type="text">
</div>
<div>
    <label for="Apellido">¿Cual es tu apellido?</label>
    <input id="Apellido" type="text">
    <p>Cual es tu opinion Sobre la CD del club?</p>
<textarea id="" cols="30" rows="10">Deja tu opinion</textarea>
<br><br>
<h2>¿Que Opinas Sobre el gringo Heinze?</h2>
<textarea id="" cols="30" rows="10">Deja tu opinion</textarea>
<br><br>
<div>
    <label for="SFORZA">¿Sforza es el mejor 5 del futbol argentino?</label>
    <input name="SFORZA" type="radio" id="Si">
    <label for="Si">Si</label>
    <input name="SFORZA" type="radio" id="No">
    <label for="No">No</label> 
</div>
</div>
</form> 
</div>



<a href="https://www.newellsoldboys.com.ar/" target="_blank">Ir a la pagina oficial del mas grande</a>
<br><br>
<a href="https://www.instagram.com/newells/?hl=es" target="_blank">Ir al instagram del mas grande</a>
<br><br>
<a href="https://twitter.com/Newells" target="_blank">Ir al twitter del mas grande</a>
<br><br>
</body>
</html>
